# @exception expected opening '(' in call to 'exists'

exists 0
