# @exception array index out of bounds: 3 >= 3

func foo() {
  return [2, 4, 8][3]
}

foo()
echo "bad"
