# @exception variable 'x' already exists in scope

{
  let x = 1
  let x = 2
}
