# @Exception

function foo() {
  return 1
}

function foo() {
  return 2
}
