# @exception multiple global definitions of 'foo'

func foo() {
  return 1
}

func foo() {
  return 2
}
